In [44]:
import numpy as np



In [45]:
#Q1
#Part a
zero=np.zeros((4,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [46]:
#Q1
#Part b
one=np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [47]:
#Q1
#part c
Identity=np.eye(5)
print(Identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
#Q1
#part d
Constant_values=np.full((3,4),7)
print(Constant_values)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [49]:
#Q1
#part d
Random_values=np.random.randint(10,99, size=(3,4))
print(Random_values)

[[20 58 85 34]
 [55 33 91 14]
 [53 36 74 90]]


In [50]:
# Q2
array=np.arange(5,50,5)
array

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [51]:
array.reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])