In [38]:
import numpy as np

In [39]:
# Q1
arr=np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
new_array_rshape=arr.reshape(3,4)
print(new_array_rshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
second_array_rshape=arr.reshape(2,6)
print(second_array_rshape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [42]:
# Q2
arr=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])


In [43]:
# Flatten array
flatten_array=arr.flatten()
print(arr)
print(flatten_array)
flatten_array[2]=100 # here the modification will occur in flatten array but not in original array
print(flatten_array) 
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[  1   2 100   4   5   6   7   8   9  10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
# Ravel array
ravel_array=arr.ravel()
print(arr)
print(ravel_array)
ravel_array[3]=500 # here the modification will occur in ravel array but also in original array
print(ravel_array)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3 500   5   6   7   8   9  10]
[[  1   2   3 500   5]
 [  6   7   8   9  10]]


In [51]:
# Q3
array=np.arange(1,10).reshape(3,3)
flatten_arr=array.flatten()
ravel_arr=array.ravel()
print(array)
flatten_arr[2]=1000
ravel_arr[3]=2000
print(array)  # here the modification in original array will only occur based on ravel array modification 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[   1    2    3]
 [2000    5    6]
 [   7    8    9]]
