In [1]:
import numpy as np

In [4]:
# Q1
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
Scalar_broadcasting=A+10
print(Scalar_broadcasting)
# Shape prediction (3,3)
B=np.array([1,2,3])
Row_broadcasting=A+B
print(Row_broadcasting)
# Shape prediction A=(3,3)B=(1,3) B will expand in (3,3).Result shape will be (3,3)
C=np.array([[1],[2],[3]])
Column_broadcasting=A+C
print(Column_broadcasting)
# Shape prediction A=(3,3)B=(3,1) B will expand in (3,3).Result shape will be (3,3)


[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
