In [11]:
import numpy as np

In [12]:
# Q1
array_A=np.random.randint(1,20, size=5)
array_B=np.random.randint(10,30,size=5)
print(array_A)
print(array_B)

[19 13 17  9 10]
[28 15 12 23 27]


In [13]:
print(array_A+array_B)
print(array_A-array_B)
print(array_A*array_B)
print(array_A/array_B)

[47 28 29 32 37]
[ -9  -2   5 -14 -17]
[532 195 204 207 270]
[0.67857143 0.86666667 1.41666667 0.39130435 0.37037037]


In [20]:
# Q2
arr=np.array([5,16,34,43,9,4,])
sqrt_values=np.sqrt(arr)
exp_values=np.exp(arr)
sin_values=np.sin(arr)
print("Squrae Root=",sqrt_values)
print("Exponential=",exp_values)
print("Sine=",sin_values)

Squrae Root= [2.23606798 4.         5.83095189 6.55743852 3.         2.        ]
Exponential= [1.48413159e+02 8.88611052e+06 5.83461743e+14 4.72783947e+18
 8.10308393e+03 5.45981500e+01]
Sine= [-0.95892427 -0.28790332  0.52908269 -0.83177474  0.41211849 -0.7568025 ]


In [31]:
# Q3
Temp_in_Celsius=np.array([35,37,36,29,41,33,32,44,27,31])
Temp_in_Farenheit=Temp_in_Celsius*9/5+32
print("Temperature in Celsius:",Temp_in_Celsius)
print("Temperature in farenheit:",Temp_in_Farenheit)

Temperature in Celsius: [35 37 36 29 41 33 32 44 27 31]
Temperature in farenheit: [ 95.   98.6  96.8  84.2 105.8  91.4  89.6 111.2  80.6  87.8]
