In [1]:
import numpy as np

In [2]:
arr=np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])

In [8]:
# Q1 Extract the second row
print(arr[1])

[50 60 70 80]


In [9]:
# Q2 Extract the first two rows and the second two columns
print(arr[0:2,1:3])

[[20 30]
 [60 70]]


In [17]:
# Q3 Extract the last column using slicing
print(arr[:3,3])


[ 40  80 120]


In [6]:
# Q4 Replace the middle row with [1,2,3,4]

In [18]:
arr[1,:4]=[1,2,3,4]
print(arr)

[[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]
